api-version: 2019-12-01
location: westeurope
name: websim
properties:
  containers:
  - name: streamlitapp
    properties:
      image: webdd.azurecr.io/websim_azure:v1
      ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
      resources:
        requests:
          cpu: 2.0
          memoryInGB: 1.5
  restartPolicy: Never
  ipAddress:
    ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
    type: Public
    dnsNameLabel: websim_cop
  osType: Linux
tags: null
type: Microsoft.ContainerInstance/containerGroups
